version: '3'
services:
  azure:
    build:
      context: docker/azure
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-storage:/var/lib/grafana
    entrypoint: ["/entrypoint.sh"]
    command: ["grafana", "server", "-homepath", "/usr/share/grafana", "-config", "/etc/grafana/grafana.ini"]

volumes:
  grafana-storage:
