version: "2.3"


services:
  client:
    build:
      context: ./docker/client
    network_mode: host  # to communicate with other ROS2 node
    environment:
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}
      - CABOT_INFLUXDB_ROBOT_NAME
      - CABOT_INFLUXDB_IMAGE_LEFT_TOPIC
      - CABOT_INFLUXDB_IMAGE_CENTER_TOPIC
      - CABOT_INFLUXDB_IMAGE_RIGHT_TOPIC
      - CABOT_INFLUXDB_IMAGE_ROTATE
      - CABOT_INFLUXDB_POSE_INTERVAL
      - CABOT_INFLUXDB_CMD_VEL_INTERVAL
      - CABOT_INFLUXDB_ODOM_INTERVAL
      - CABOT_INFLUXDB_DIAG_AGG_INTERVAL
      - CABOT_INFLUXDB_IMAGE_INTERVAL
      - CABOT_INFLUXDB_HOST
      - CABOT_INFLUXDB_TOKEN
      - CABOT_INFLUXDB_ORG
      - CABOT_INFLUXDB_BUCKET
    volumes:
      - ./docker/home:/home/developer/
      - ${CABOT_ANCHOR_FILE:-./zero-anchor.yaml}:/home/developer/ros2_ws/src/anchor_file.yaml
      - ./cabot_influxdb_client:/home/developer/ros2_ws/src/cabot_influxdb_client
      - ./cabot-common/cabot_msgs:/home/developer/ros2_ws/src/cabot_msgs
    command:
      - ./launch.sh
      - launch

networks:
  grafana_network:
    name: grafana_network
