version: "2.3"


services:
  client:
    build:
      context: ./docker/client
    network_mode: host  # to communicate with other ROS2 node
    environment:
      - RMW_IMPLEMENTATION=$(RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}
      - CABOT_INFLUXDB_HOST=${CABOT_INFLUXDB_HOST:-localhost}
      - CABOT_INFLUXDB_TOKEN=${CABOT_INFLUXDB_TOKEN:-a54a87f7-73a0-4534-9741-ad7ff4e7d111}
      - CABOT_INFLUXDB_ORG=${CABOT_INFLUXDB_ORG:-cabot}
      - CABOT_INFLUXDB_BUCKET=${CABOT_INFLUXDB_ORG:-cabot}
    volumes:
      - ./docker/home:/home/developer/
      - ./cabot_influxdb_client:/home/developer/ros2_ws/src/cabot_influxdb_client
      - ./cabot-common/cabot_msgs:/home/developer/ros2_ws/src/cabot_msgs
    command:
      - ./launch.sh
      - launch

networks:
  grafana_network:
    name: grafana_network
