version: "2.3"


services:
  influxdb:
    build:
      context: docker/influxdb
    networks:
      - grafana_network
    ports:
      - 127.0.0.1:8086:8086
    volumes:
      - ./influxdb:/var/lib/influxdb2

  dev:
    build:
      context: docker/dev
    networks:
      - grafana_network
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./docker/home:/home/developer
      - ./grafana:/home/developer/src/grafana
    command:
      - /launch.sh
      - launch

networks:
  grafana_network:
    name: grafana_network
