name: Run Unittest

on:
  push:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  run_unittest:
    runs-on: ubuntu-20.04
    steps:  
    # - name: Maximize build space
    #   run:  |
    #         sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
    #         sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
    #         sudo rm -rf /opt/ghc
    #         echo "Available storage:"
    #         df -h
    #         docker system prune -a --volumes -f # delete unnecessary preinstalled docker images
            
    - uses: actions/checkout@v4

    - name: Install vcs
      run: pip3 install vcstool

    - name: Prepare thirdparty repos
      run: ./setup-dependency.sh

    - name: Pull images
      shell: bash
      run: docker pull cmucal/cabot-influxdb-client:latest

    - name: Run unittest
      shell: bash
      run:  |
             export HOST_UID=$(id -u)
             export HOST_GID=$(id -g)
             docker compose run --rm influxdb-client-dev bash -c "pwd && /home/developer/ros2_ws/unittest.sh -b -a"
