{
 "title": "CaBot Test",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "robot_name",
    "query": "cabot1, cabot2, cabot3, cabot4, cabot5, cabot6, cabot7, cabot8, cabot9, cabot10"
   }
  ]
 },
 "panels": [
  {
   "title": "${robot_name}",
   "type": "table",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "repeat": "robot_name",
   "targets": [
    {
     "query": "// Query for measurement1\ndata1 = from(bucket: \"cabot\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"tour\")\n  |> filter(fn: (r) => r._field == \"data\")\n  |> filter(fn: (r) => r.robot_name == \"${robot_name}\")\n  |> map(fn: (r) => ({ r with data: r._value }))\n  |> map(fn: (r) => ({ r with key: 1 }))\n  //|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> last(column: \"_time\")\n  |> keep(columns: [\"data\", \"key\"])\n\ndata2 = from(bucket: \"cabot\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"destination\")\n  |> filter(fn: (r) => r._field == \"data\")\n  |> filter(fn: (r) => r.robot_name == \"${robot_name}\")\n  |> map(fn: (r) => ({ r with data: r._value }))\n  |> map(fn: (r) => ({ r with key: 2 }))\n  //|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> last(column: \"_time\")\n  |> keep(columns: [\"data\", \"key\"])\n\n\nunion(tables: [data1, data2])\n  |> sort(columns: [\"key\"])\n  |> keep(columns: [\"data\"])"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 1, "x": 2, "y": 0 },
   "repeat": "robot_name",
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"cabot\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r._measurement == \"odometry\")\n  |> filter(fn: (r) => r._field == \"linear\")\n  |> filter(fn: (r) => r.robot_name == \"${robot_name}\")\n"
    }
   ]
  },
  {
   "title": "Rotation",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 1, "x": 3, "y": 0 },
   "repeat": "robot_name",
   "fieldConfig": { "defaults": { "unit": "rotdegs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"cabot\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r._measurement == \"odometry\")\n  |> filter(fn: (r) => r._field == \"angular\")\n  |> filter(fn: (r) => r.robot_name == \"${robot_name}\")\n  |> map(fn: (r) => ({ r with _value: r._value / 3.141592 * -180.0 }))\n"
    }
   ]
  },
  {
   "title": "Speed History",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "repeat": "robot_name",
   "targets": [
    {
     "query": "from(bucket: \"cabot\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r._measurement == \"odometry\")\n  |> filter(fn: (r) => r._field == \"linear\")\n  |> filter(fn: (r) => r.robot_name == \"${robot_name}\")\n"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 1, "x": 6, "y": 0 },
   "repeat": "robot_name",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"cabot\")\n  |> range(start: -1m)  // Adjust the time range as needed\n  |> filter(fn: (r) => r._measurement == \"battery\")\n  |> filter(fn: (r) => r._field == \"percentage\")\n  |> filter(fn: (r) => r.robot_name == \"${robot_name}\")"
    }
   ]
  },
  {
   "title": "Diagnostics",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "repeat": "robot_name",
   "targets": [
    {
     "query": "from(bucket: \"cabot\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"diagnostic\")\n  |> filter(fn: (r) => r._field == \"level\" or r._field == \"name\")\n  |> filter(fn: (r) => r.robot_name == \"${robot_name}\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"name\", \"level\"])\n\n\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "repeat": "robot_name",
   "targets": [
    {
     "query": "from(bucket: \"cabot\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r._measurement == \"image\")\n  |> filter(fn: (r) => r._field == \"data\")\n  |> filter(fn: (r) => r[\"format\"] == \"jpeg\")\n  |> filter(fn: (r) => r.direction == \"left\")\n  |> filter(fn: (r) => r.robot_name == \"${robot_name}\")\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "repeat": "robot_name",
   "targets": [
    {
     "query": "from(bucket: \"cabot\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r._measurement == \"image\")\n  |> filter(fn: (r) => r._field == \"data\")\n  |> filter(fn: (r) => r[\"format\"] == \"jpeg\")\n  |> filter(fn: (r) => r.direction == \"center\")\n  |> filter(fn: (r) => r.robot_name == \"${robot_name}\")\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "repeat": "robot_name",
   "targets": [
    {
     "query": "from(bucket: \"cabot\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r._measurement == \"image\")\n  |> filter(fn: (r) => r._field == \"data\")\n  |> filter(fn: (r) => r[\"format\"] == \"jpeg\")\n  |> filter(fn: (r) => r.direction == \"right\")\n  |> filter(fn: (r) => r.robot_name == \"${robot_name}\")\n"
    }
   ]
  },
  {
   "title": "Robot Location",
   "type": "geomap",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "repeat": "robot_name",
   "targets": [
    {
     "query": "from(bucket: \"cabot\")\n  |> range(start: -5m)  // Adjust the time range as needed\n  |> filter(fn: (r) => r._measurement == \"pose_data\")\n  |> filter(fn: (r) => r._field == \"lat\" or r._field == \"lng\" or r._field == \"yaw\")\n  |> filter(fn: (r) => r.robot_name == \"${robot_name}\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"lat\", \"lng\", \"yaw\", \"robot_name\"])\n  |> last(column: \"_time\")\n  |> map(fn: (r) => ({\n      r with\n      _value: r._value,\n      seriesName: r.robot_name\n    }))"
    },
    {
     "query": "from(bucket: \"cabot\")\n  |> range(start: -1m)  // Adjust the time range as needed\n  |> filter(fn: (r) => r._measurement == \"pose_data\")\n  |> filter(fn: (r) => r._field == \"lat\" or r._field == \"lng\" or r._field == \"yaw\")\n  |> filter(fn: (r) => r.robot_name == \"${robot_name}\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"lat\", \"lng\", \"yaw\", \"robot_name\"])"
    },
    {
     "query": "from(bucket: \"cabot\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"plan\")\n  |> filter(fn: (r) => r._field == \"lat\" or r._field == \"lng\")\n  |> filter(fn: (r) => r.robot_name == \"${robot_name}\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"lat\", \"lng\", \"robot_name\"])\n"
    }
   ]
  },
  {
   "title": "Robot Location",
   "type": "geomap",
   "gridPos": { "h": 40, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"cabot\")\n  |> range(start: -5m)  // Adjust the time range as needed\n  |> filter(fn: (r) => r._measurement == \"pose_data\")\n  |> filter(fn: (r) => r._field == \"lat\" or r._field == \"lng\" or r._field == \"yaw\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"lat\", \"lng\", \"yaw\", \"robot_name\"])\n  |> group(columns: [\"robot_name\"])\n  |> last(column: \"_time\")\n  |> map(fn: (r) => ({\n      r with\n      _value: r._value,\n      seriesName: r.robot_name\n    }))"
    },
    {
     "query": "from(bucket: \"cabot\")\n  |> range(start: -1m)  // Adjust the time range as needed\n  |> filter(fn: (r) => r._measurement == \"pose_data\")\n  |> filter(fn: (r) => r._field == \"lat\" or r._field == \"lng\" or r._field == \"yaw\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"lat\", \"lng\", \"yaw\", \"robot_name\"])\n  |> group(columns: [\"robot_name\"])"
    },
    {
     "query": "from(bucket: \"cabot\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"plan\")\n  |> filter(fn: (r) => r._field == \"lat\" or r._field == \"lng\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"lat\", \"lng\", \"robot_name\"])\n  |> group(columns: [\"robot_name\"])\n"
    }
   ]
  }
 ]
}